# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty

# Setup
title:               AI, Deep and Reinforcement Learning
tagline:             ''
description:         ''
url:                 https://jandumke.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jan Dumke
#  url:
#  email:

# Custom vars
#version:             1.0.0

authors:
  Jan:
    display_name: Jan Dumke
    #gravatar: 60fd5218fff6927c0ed376cce01c5460
    #email: matt@lostdecadegames.com
    #web: http://www.richtaur.com/
    #twitter: richtaur
    #github: richtaur
